- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: 'Install dependencies'
    apt:
      pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
      - python-setuptools
  - name: "Docker key"
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "Add docker repo"
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - name: "Install docker-ce"
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  - name: "Docker is started"
    service: 
      name: docker
      state: started
  - name: "Install Docker pip package"
    pip: 
      name: docker
      executable: pip3
  - name: "Adding Bujanovakatia user to the docker group"
    user:
      name: bujanovakatia
      group: docker
      append: yes
  - name: "Reset the connection"
    meta: reset_connection  
